"""make document parsed_at timezone-aware

Revision ID: 6337215a1a71
Revises: eb9b6f5b4e2e
Create Date: 2026-07-31 14:15:06.450019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6337215a1a71'
down_revision: Union[str, None] = 'eb9b6f5b4e2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_application_notes_application_id'), 'application_notes', ['application_id'], unique=False)
    op.create_index(op.f('ix_application_status_history_application_id'), 'application_status_history', ['application_id'], unique=False)
    op.create_index(op.f('ix_applications_candidate_id'), 'applications', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_applications_job_id'), 'applications', ['job_id'], unique=False)
    op.alter_column('documents', 'parsed_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.create_index(op.f('ix_interview_rounds_application_id'), 'interview_rounds', ['application_id'], unique=False)
    op.create_index(op.f('ix_interview_rounds_conducted_by'), 'interview_rounds', ['conducted_by'], unique=False)
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_index(op.f('ix_interview_rounds_conducted_by'), table_name='interview_rounds')
    op.drop_index(op.f('ix_interview_rounds_application_id'), table_name='interview_rounds')
    op.alter_column('documents', 'parsed_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_index(op.f('ix_applications_job_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_candidate_id'), table_name='applications')
    op.drop_index(op.f('ix_application_status_history_application_id'), table_name='application_status_history')
    op.drop_index(op.f('ix_application_notes_application_id'), table_name='application_notes')
    # ### end Alembic commands ###
